### ISSUE TITLE
compiling/using it under Linux?

### ISSUE THREAD

**Issue by freddiaN** [PazerOP/CastingEssentials#39]
Hello,

would there be a way to compile this under Unix/Linux, or are there features used that are known to _**only**_ exist under Windows? I mean technically it's _just_ a VS project -> C++, so there may be a way to compile it.
 I know that I would probably be the only one that would use it under Linux, but it would still be nice.
(couldn't post on tf.tv, since it for some reason doesn't let me log in)

**Comment by PazerOP** [comment]
As far as I know, there's shouldn't be any code that relies on Windows. I try to keep WINAPI stuff out of my programming in general when there are similar alternatives available. That being said, most or all of the signatures will be different for Linux compared to the Windows builds of TF2 since a different compiler is used.

While I do not personally have the time or expertise to port this to Linux, not much work should be required to get it working on Linux outside the essentials (DllMain, signatures).

**Comment by freddiaN** [comment]
I'm going to try and do some porting myself (even tho I have like no programming experience) and if I achieve anything, I'll let you know...
